# Generated by Django 3.2.25 on 2026-06-06 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0017_alter_log_logtype"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="emergency_contact_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="emergency_contact_phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="emergency_contact_relationship",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
