# Generated by Django 3.2.25 on 2026-06-06 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0017_alter_log_logtype"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="discord_handle",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
