# Generated by Django 3.2.25 on 2026-06-14 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0018_discord_handle"),
        ("profile", "0018_emergency_contact"),
    ]

    operations = []
