# Generated by Django 3.2.25 on 2026-06-08 10:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0025_terms_accepted_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="rfid",
            field=models.CharField(
                blank=True,
                max_length=8,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{1,8}$", "RFID tag must be 1-8 digits."
                    )
                ],
                verbose_name="RFID Tag",
            ),
        ),
    ]
