name: JavaScript Linter (eslint)
on: [pull_request]
jobs:
  lint-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - name: Install modules
        working-directory: ./src-frontend
        run: npm i
      - name: Run ESLint
        working-directory: ./src-frontend
        run: npm run lint
