name: "Semgrep SAST Analysis"
on: [pull_request]

jobs:
  semgrep:
    name: Security Scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Semgrep
      run: pip install semgrep

    # Run the open-source community rulesets (OWASP top 10, security, etc.)
    - name: Run Semgrep Scan
      run: semgrep scan --config auto
